export const data = [
  {
    question: "What is the main function of the Election Commission of Nepal?",
    option1: "Conducting elections",
    option2: "Maintaining law and order",
    option3: "Managing foreign relations",
    option4: "Overseeing national security",
    ans: 1,
  },
  {
    question: "How many members are there in the Election Commission of Nepal?",
    option1: "Two",
    option2: "Three",
    option3: "Five",
    option4: "Seven",
    ans: 3,
  },
  {
    question: "Which document is required for voter registration in Nepal?",
    option1: "Citizenship certificate",
    option2: "Passport",
    option3: "Driving license",
    option4: "National ID card",
    ans: 1,
  },
  {
    question: "What is the minimum age required to vote in Nepal?",
    option1: "16 years",
    option2: "18 years",
    option3: "20 years",
    option4: "21 years",
    ans: 2,
  },
  {
    question: "When was the Election Commission of Nepal established?",
    option1: "1947",
    option2: "1951",
    option3: "1955",
    option4: "1960",
    ans: 2,
  },
];
