function generateJoke() {
  const jokes = [
    "Rajesh Hamal doesn't do push-ups. He pushes the Earth down.",
    "When Rajesh Hamal enters water, he doesn’t get wet. The water gets Rajesh Hamal-ed.",
    "Rajesh Hamal once threw a grenade and killed 50 people. Then the grenade exploded.",
    "Rajesh Hamal can slam a revolving door.",
    "When Rajesh Hamal looks at the sky, the stars get jealous of his shine.",
    "Rajesh Hamal doesn’t need Google. Google needs Rajesh Hamal.",
    "When Rajesh Hamal cracks a joke, reality changes to make it true.",
    "Rajesh Hamal counted to infinity. Twice.",
    "Rajesh Hamal can divide by zero.",
    "Rajesh Hamal doesn’t sleep. He waits.",
    "When Rajesh Hamal steps on a Lego, the Lego cries.",
    "Rajesh Hamal once beat the sun in a staring contest.",
    "Rajesh Hamal’s calendar goes straight from March 31st to April 2nd. No one fools Rajesh Hamal.",
    "Rajesh Hamal can unscramble an egg.",
    "Rajesh Hamal’s shadow has never left him. It’s too scared.",
    "Rajesh Hamal doesn’t need a GPS. He decides where he is.",
    "When Rajesh Hamal watches a scary movie, the monsters get scared.",
    "Rajesh Hamal can speak Braille.",
    "Rajesh Hamal doesn’t do laundry. Dirt is too afraid to touch his clothes.",
    "When Rajesh Hamal does a math problem, calculators ask for his help.",
    "Rajesh Hamal once won a game of chess with one move: looking at the board.",
    "Rajesh Hamal can clap with one hand.",
    "When Rajesh Hamal smiles, the sun takes notes.",
    "Rajesh Hamal’s tears cure cancer. Too bad he has never cried.",
    "Rajesh Hamal can eat just one Lay’s chip and stop.",
    "When Rajesh Hamal says, 'I’ll be there in five minutes,' time slows down.",
    "Rajesh Hamal once built a snowman out of rain.",
    "Rajesh Hamal doesn’t wear a watch. He decides what time it is.",
    "When Rajesh Hamal calls a wrong number, the phone apologizes.",
    "Rajesh Hamal can win a game of hide-and-seek without hiding.",
    "Rajesh Hamal can light a fire by rubbing two ice cubes together.",
    "When Rajesh Hamal whispers, mountains move.",
    "Rajesh Hamal never gets lost. The road bends to his will.",
    "Rajesh Hamal once defeated gravity. It hasn’t dared to return since.",
    "Rajesh Hamal doesn’t need a parachute. The ground catches him softly.",
    "When Rajesh Hamal enters a contest, everyone else quits.",
    "Rajesh Hamal can finish a book by closing its cover.",
    "Rajesh Hamal can divide a circle into three halves.",
    "When Rajesh Hamal claps, lightning strikes in response.",
    "Rajesh Hamal can spell 'impossible' backwards while blindfolded.",
    "Rajesh Hamal once went to Mars. That’s why there’s no life there now.",
    "Rajesh Hamal can jump-start a car by looking at it.",
    "Rajesh Hamal never waits in line. Lines rearrange themselves for him.",
    "Rajesh Hamal once scared a ghost to death.",
    "Rajesh Hamal doesn’t age. Time is too respectful to touch him.",
    "When Rajesh Hamal enters a room, Wi-Fi signals get stronger.",
    "Rajesh Hamal’s signature changes every time he writes it. It’s always original.",
    "Rajesh Hamal doesn’t get hungry. Food comes to him willingly.",
    "When Rajesh Hamal loses a game, the game reprograms itself so he wins.",
  ];
}
